package Principal;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.EmptyBorder;

public class MenuPrincipal extends javax.swing.JFrame {

    int x, y;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.btnComputadoras.setSelected(true);

        new CambiarPanel(pnlPrincipal, new Paneles.pnlComputadoras());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        menuLat = new javax.swing.JPanel();
        sesiones = new rsbuttom.RSButtonMetro();
        btnConsumo = new rsbuttom.RSButtonMetro();
        btnFacturacion = new rsbuttom.RSButtonMetro();
        btnComputadoras = new rsbuttom.RSButtonMetro();
        configuracion = new rsbuttom.RSButtonMetro();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Lan Center");
        setBackground(new java.awt.Color(230, 221, 221));
        setPreferredSize(new java.awt.Dimension(960, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 1000));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlTop.setBackground(new java.awt.Color(204, 255, 255));
        pnlTop.setMaximumSize(new java.awt.Dimension(32767, 50));
        pnlTop.setMinimumSize(new java.awt.Dimension(349, 50));
        pnlTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTopMouseDragged(evt);
            }
        });
        pnlTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTopMousePressed(evt);
            }
        });
        pnlTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 3));

        jToggleButton1.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButton1.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon("I:\\PF_POO\\GestionLanCenter\\src\\Imagenes\\menu.png")); // NOI18N
        jToggleButton1.setBorder(null);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        pnlTop.add(jToggleButton1);

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 3, 36)); // NOI18N
        jLabel1.setText("Gestion Lan Center");
        pnlTop.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.01;
        jPanel1.add(pnlTop, gridBagConstraints);

        menuLat.setBackground(new java.awt.Color(204, 204, 204));
        menuLat.setPreferredSize(new java.awt.Dimension(100, 900));

        sesiones.setIcon(new javax.swing.ImageIcon("I:\\PF_POO\\GestionLanCenter\\src\\Imagenes\\Sesiones.png")); // NOI18N
        sesiones.setText("Sesiones");
        sesiones.setColorBorde(null);
        sesiones.setColorNormal(new java.awt.Color(240, 240, 240));
        sesiones.setColorTextHover(new java.awt.Color(153, 153, 153));
        sesiones.setColorTextNormal(new java.awt.Color(0, 0, 0));
        sesiones.setColorTextPressed(new java.awt.Color(153, 153, 153));
        sesiones.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sesiones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sesiones.setOpaque(false);
        sesiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sesionesMousePressed(evt);
            }
        });
        sesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesionesActionPerformed(evt);
            }
        });

        btnConsumo.setIcon(new javax.swing.ImageIcon("I:\\PF_POO\\GestionLanCenter\\src\\Imagenes\\Consumo.png")); // NOI18N
        btnConsumo.setText("Consumo");
        btnConsumo.setColorBorde(null);
        btnConsumo.setColorNormal(new java.awt.Color(240, 240, 240));
        btnConsumo.setColorTextHover(new java.awt.Color(153, 153, 153));
        btnConsumo.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnConsumo.setColorTextPressed(new java.awt.Color(153, 153, 153));
        btnConsumo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnConsumo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsumo.setOpaque(false);
        btnConsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConsumoMousePressed(evt);
            }
        });
        btnConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsumoActionPerformed(evt);
            }
        });

        btnFacturacion.setIcon(new javax.swing.ImageIcon("I:\\PF_POO\\GestionLanCenter\\src\\Imagenes\\Factura.png")); // NOI18N
        btnFacturacion.setText("Facturacion");
        btnFacturacion.setColorBorde(null);
        btnFacturacion.setColorNormal(new java.awt.Color(240, 240, 240));
        btnFacturacion.setColorTextHover(new java.awt.Color(153, 153, 153));
        btnFacturacion.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnFacturacion.setColorTextPressed(new java.awt.Color(153, 153, 153));
        btnFacturacion.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnFacturacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFacturacion.setOpaque(false);
        btnFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFacturacionMousePressed(evt);
            }
        });
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });

        btnComputadoras.setIcon(new javax.swing.ImageIcon("I:\\PF_POO\\GestionLanCenter\\src\\Imagenes\\Computadoras.png")); // NOI18N
        btnComputadoras.setText("Computadoras");
        btnComputadoras.setColorBorde(null);
        btnComputadoras.setColorNormal(new java.awt.Color(240, 240, 240));
        btnComputadoras.setColorTextHover(new java.awt.Color(153, 153, 153));
        btnComputadoras.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnComputadoras.setColorTextPressed(new java.awt.Color(153, 153, 153));
        btnComputadoras.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnComputadoras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnComputadoras.setOpaque(false);
        btnComputadoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnComputadorasMousePressed(evt);
            }
        });
        btnComputadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputadorasActionPerformed(evt);
            }
        });

        configuracion.setIcon(new javax.swing.ImageIcon("I:\\PF_POO\\GestionLanCenter\\src\\Imagenes\\Configuracion.png")); // NOI18N
        configuracion.setText("Configuracion");
        configuracion.setColorBorde(null);
        configuracion.setColorNormal(new java.awt.Color(240, 240, 240));
        configuracion.setColorTextHover(new java.awt.Color(153, 153, 153));
        configuracion.setColorTextNormal(new java.awt.Color(0, 0, 0));
        configuracion.setColorTextPressed(new java.awt.Color(153, 153, 153));
        configuracion.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        configuracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        configuracion.setOpaque(false);
        configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                configuracionMousePressed(evt);
            }
        });
        configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLatLayout = new javax.swing.GroupLayout(menuLat);
        menuLat.setLayout(menuLatLayout);
        menuLatLayout.setHorizontalGroup(
            menuLatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLatLayout.createSequentialGroup()
                            .addComponent(btnFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27))
                        .addComponent(btnComputadoras, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        menuLatLayout.setVerticalGroup(
            menuLatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLatLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(sesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnComputadoras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(menuLat, gridBagConstraints);

        pnlPrincipal.setLayout(new java.awt.GridLayout(1, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(pnlPrincipal, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        int posicion = menuLat.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, menuLat);
        } else {
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, menuLat);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void pnlTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseDragged
        // TODO add your handling code here:
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_pnlTopMouseDragged

    private void pnlTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlTopMousePressed

    private void configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(pnlPrincipal, new Paneles.pnlConfiguracion());
        if (this.configuracion.isSelected()) {
            this.configuracion.setColorNormal(new Color(239, 238, 244));
            this.configuracion.setColorHover(new Color(204, 204, 204));
            this.configuracion.setColorPressed(new Color(204, 204, 204));

            this.btnComputadoras.setColorNormal(new Color(204, 204, 204));
            this.btnComputadoras.setColorHover(new Color(204, 204, 204));
            this.btnComputadoras.setColorPressed(new Color(204, 204, 204));

            this.sesiones.setColorNormal(new Color(239, 238, 244));
            this.sesiones.setColorHover(new Color(204, 204, 204));
            this.sesiones.setColorPressed(new Color(204, 204, 204));

            this.btnConsumo.setColorNormal(new Color(239, 238, 244));
            this.btnConsumo.setColorHover(new Color(204, 204, 204));
            this.btnConsumo.setColorPressed(new Color(204, 204, 204));

            this.btnFacturacion.setColorNormal(new Color(239, 238, 244));
            this.btnFacturacion.setColorHover(new Color(204, 204, 204));
            this.btnFacturacion.setColorPressed(new Color(204, 204, 204));

        } else {
            this.configuracion.setColorNormal(new Color(239, 238, 244));
            this.configuracion.setColorHover(new Color(204, 204, 204));
            this.configuracion.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_configuracionActionPerformed

    private void configuracionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configuracionMousePressed
        // TODO add your handling code here:
        this.btnComputadoras.setSelected(false);
        this.sesiones.setSelected(false);
        this.btnConsumo.setSelected(false);
        this.btnFacturacion.setSelected(false);
        this.configuracion.setSelected(true);
    }//GEN-LAST:event_configuracionMousePressed

    private void btnComputadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputadorasActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(pnlPrincipal, new Paneles.pnlComputadoras());
        if (this.btnComputadoras.isSelected()) {
            this.btnComputadoras.setColorNormal(new Color(204, 204, 204));
            this.btnComputadoras.setColorHover(new Color(204, 204, 204));
            this.btnComputadoras.setColorPressed(new Color(204, 204, 204));

            this.sesiones.setColorNormal(new Color(239, 238, 244));
            this.sesiones.setColorHover(new Color(204, 204, 204));
            this.sesiones.setColorPressed(new Color(204, 204, 204));

            this.btnConsumo.setColorNormal(new Color(239, 238, 244));
            this.btnConsumo.setColorHover(new Color(204, 204, 204));
            this.btnConsumo.setColorPressed(new Color(204, 204, 204));

            this.btnFacturacion.setColorNormal(new Color(239, 238, 244));
            this.btnFacturacion.setColorHover(new Color(204, 204, 204));
            this.btnFacturacion.setColorPressed(new Color(204, 204, 204));

            this.configuracion.setColorNormal(new Color(239, 238, 244));
            this.configuracion.setColorHover(new Color(204, 204, 204));
            this.configuracion.setColorPressed(new Color(204, 204, 204));

        } else {
            this.btnComputadoras.setColorNormal(new Color(239, 238, 244));
            this.btnComputadoras.setColorHover(new Color(204, 204, 204));
            this.btnComputadoras.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btnComputadorasActionPerformed

    private void btnComputadorasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComputadorasMousePressed
        // TODO add your handling code here:
        this.btnComputadoras.setSelected(true);
        this.sesiones.setSelected(false);
        this.btnConsumo.setSelected(false);
        this.btnFacturacion.setSelected(false);
        this.configuracion.setSelected(false);
    }//GEN-LAST:event_btnComputadorasMousePressed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(pnlPrincipal, new Paneles.pnlFacturacion());
        if (this.btnFacturacion.isSelected()) {
            this.btnFacturacion.setColorNormal(new Color(239, 238, 244));
            this.btnFacturacion.setColorHover(new Color(204, 204, 204));
            this.btnFacturacion.setColorPressed(new Color(204, 204, 204));

            this.btnComputadoras.setColorNormal(new Color(204, 204, 204));
            this.btnComputadoras.setColorHover(new Color(204, 204, 204));
            this.btnComputadoras.setColorPressed(new Color(204, 204, 204));

            this.sesiones.setColorNormal(new Color(239, 238, 244));
            this.sesiones.setColorHover(new Color(204, 204, 204));
            this.sesiones.setColorPressed(new Color(204, 204, 204));

            this.btnConsumo.setColorNormal(new Color(239, 238, 244));
            this.btnConsumo.setColorHover(new Color(204, 204, 204));
            this.btnConsumo.setColorPressed(new Color(204, 204, 204));

            this.configuracion.setColorNormal(new Color(239, 238, 244));
            this.configuracion.setColorHover(new Color(204, 204, 204));
            this.configuracion.setColorPressed(new Color(204, 204, 204));

        } else {
            this.btnFacturacion.setColorNormal(new Color(239, 238, 244));
            this.btnFacturacion.setColorHover(new Color(204, 204, 204));
            this.btnFacturacion.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btnFacturacionActionPerformed

    private void btnFacturacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturacionMousePressed
        // TODO add your handling code here:
        this.btnComputadoras.setSelected(false);
        this.sesiones.setSelected(false);
        this.btnConsumo.setSelected(false);
        this.btnFacturacion.setSelected(true);
        this.configuracion.setSelected(false);
    }//GEN-LAST:event_btnFacturacionMousePressed

    private void btnConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsumoActionPerformed
        // TODO add your handling code here:
        btnConsumo.setBorder(new EmptyBorder(10,0,10,0));
        new CambiarPanel(pnlPrincipal, new Paneles.pnlConsumo());
        if (this.btnConsumo.isSelected()) {
            this.btnConsumo.setColorNormal(new Color(239, 238, 244));
            this.btnConsumo.setColorHover(new Color(204, 204, 204));
            this.btnConsumo.setColorPressed(new Color(204, 204, 204));

            this.btnComputadoras.setColorNormal(new Color(204, 204, 204));
            this.btnComputadoras.setColorHover(new Color(204, 204, 204));
            this.btnComputadoras.setColorPressed(new Color(204, 204, 204));

            this.sesiones.setColorNormal(new Color(239, 238, 244));
            this.sesiones.setColorHover(new Color(204, 204, 204));
            this.sesiones.setColorPressed(new Color(204, 204, 204));

            this.btnFacturacion.setColorNormal(new Color(239, 238, 244));
            this.btnFacturacion.setColorHover(new Color(204, 204, 204));
            this.btnFacturacion.setColorPressed(new Color(204, 204, 204));

            this.configuracion.setColorNormal(new Color(239, 238, 244));
            this.configuracion.setColorHover(new Color(204, 204, 204));
            this.configuracion.setColorPressed(new Color(204, 204, 204));

        } else {
            this.btnConsumo.setColorNormal(new Color(239, 238, 244));
            this.btnConsumo.setColorHover(new Color(204, 204, 204));
            this.btnConsumo.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btnConsumoActionPerformed

    private void btnConsumoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsumoMousePressed
        // TODO add your handling code here:
        this.btnComputadoras.setSelected(false);
        this.sesiones.setSelected(false);
        this.btnConsumo.setSelected(true);
        this.btnFacturacion.setSelected(false);
        this.configuracion.setSelected(false);
    }//GEN-LAST:event_btnConsumoMousePressed

    private void sesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesionesActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(pnlPrincipal, new Paneles.pnlSesiones());
        if (this.sesiones.isSelected()) {
            this.sesiones.setColorNormal(new Color(204, 204, 204));
            this.sesiones.setColorHover(new Color(204, 204, 204));
            this.sesiones.setColorPressed(new Color(204, 204, 204));

            this.btnComputadoras.setColorNormal(new Color(239, 238, 244));
            this.btnComputadoras.setColorHover(new Color(204, 204, 204));
            this.btnComputadoras.setColorPressed(new Color(204, 204, 204));

            this.btnConsumo.setColorNormal(new Color(239, 238, 244));
            this.btnConsumo.setColorHover(new Color(204, 204, 204));
            this.btnConsumo.setColorPressed(new Color(204, 204, 204));

            this.btnFacturacion.setColorNormal(new Color(239, 238, 244));
            this.btnFacturacion.setColorHover(new Color(204, 204, 204));
            this.btnFacturacion.setColorPressed(new Color(204, 204, 204));

            this.configuracion.setColorNormal(new Color(239, 238, 244));
            this.configuracion.setColorHover(new Color(204, 204, 204));
            this.configuracion.setColorPressed(new Color(204, 204, 204));

        } else {
            this.sesiones.setColorNormal(new Color(239, 238, 244));
            this.sesiones.setColorHover(new Color(204, 204, 204));
            this.sesiones.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_sesionesActionPerformed

    private void sesionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sesionesMousePressed
        // TODO add your handling code here:
        this.btnComputadoras.setSelected(false);
        this.sesiones.setSelected(true);
        this.btnConsumo.setSelected(false);
        this.btnFacturacion.setSelected(false);
        this.configuracion.setSelected(false);
    }//GEN-LAST:event_sesionesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new MenuPrincipal().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnComputadoras;
    private rsbuttom.RSButtonMetro btnConsumo;
    private rsbuttom.RSButtonMetro btnFacturacion;
    private rsbuttom.RSButtonMetro configuracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel menuLat;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTop;
    private rsbuttom.RSButtonMetro sesiones;
    // End of variables declaration//GEN-END:variables
}
