package Vista;

import Componentes.PanelComputadora;
import DAO.ComputadoraDAO;
import Modelo.Computadora;
import java.util.List;

public class pnlComputadoras extends javax.swing.JPanel {

    public pnlComputadoras() {
        initComponents();

        List<Computadora> pcs = ComputadoraDAO.obtenerTodas();
        for (Computadora pc : pcs) {
            PanelComputadora tarjeta = new PanelComputadora(pc);
            JPanelContenedorPCs.add(tarjeta); // este panel lo agregas tú en diseño
        }

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelContenedorPCs = new javax.swing.JPanel();

        JPanelContenedorPCs.setLayout(new java.awt.GridLayout(4, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(JPanelContenedorPCs, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(JPanelContenedorPCs, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelContenedorPCs;
    // End of variables declaration//GEN-END:variables
}
